# A basic experiment

# Load the ToothGrowth dataset
data(ToothGrowth)

# Perform a two-sided t-test
t.test(x =ToothGrowth$len, alternative = "two.sided", mu = 18)

# Randomization

# Perform a t-test
ToothGrowth_ttest <- t.test(len ~ supp, data = ToothGrowth)

# Load broom
library(broom)

# Tidy ToothGrowth_ttest
tidy(ToothGrowth_ttest)

# Replication

# Load dplyr
library(dplyr)

# Count number of observations for each combination of supp and dose
data(ToothGrowth) 
ToothGrowth%>% 
    count(supp, dose) 
 
# Blocking
# Create a boxplot with geom_boxplot()
ggplot(ToothGrowth, aes(x = dose, y = len)) + 
    geom_boxplot()

# Create ToothGrowth_aov
ToothGrowth_aov <- aov(len ~ dose + supp, data = ToothGrowth)

# Examine ToothGrowth_aov with summary()
summary(ToothGrowth_aov)

# One sided vs. Two-sided tests
t.test(x = ToothGrowth$len,
         alternative = "greater",
         mu = 18)
         
# Power & Sample Size Calculations

# Load the pwr package
library(pwr)

# Calculate power
pwr.t.test(n = 100, 
             d = 0.35,
             sig.level = 0.10,
             type = "two.sample", 
             alternative = "two.sided",
             power = NULL)
             
# Calculate sample size
pwr.t.test(n = NULL,
           d = 0.25, 
           sig.level = 0.05, 
           type = "one.sample", 
           alternative = "greater", 
           power = 0.8)
           
           
   
   
   
   
